server:
  port: 8088
xxl:
  job:
    admin:
      address: http://localhost:8089/xxl-job-admin
    executor:
      appname: user-center
      ip: 127.0.0.1
      port: 9999
      logpath: ./logs/xxl-job
      logretentiondays: 30
hystrix:
  dashboard:
    proxy-stream-allow-list: localhost
  metrics:
    enabled: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
spring:
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      enabled: true