server:
  port: 8080
spring:
  security:
    user:
      name: root
      password: root
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/lgh?serverTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.mybatis.mapper: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
