server:
  port: 8082
spring:
  application:
    name: client-api
  security:
    user:
      name: root
      password: root
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://admin:admin123456@127.0.0.1:8761/eureka/
# 可以指定禁用ribbon，指定服务器请求
#    enabled: false
#user-center:
#  ribbon:
#    listOfServers: localhost:8085